# object to be detected, can be empty for default object names
string object_name

---
# header
std_msgs/Header header

# poses of detected objects
geometry_msgs/Pose[] object_poses

# success 
bool success

# score
float32 score 
